# Generated by Django 5.0.1 on 2024-02-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("is_agreed", models.BooleanField(verbose_name="Соглашение")),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
                "indexes": [
                    models.Index(fields=["id"], name="app_miscell_id_ac720a_idx"),
                    models.Index(fields=["title"], name="app_miscell_title_d90eef_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок Вопроса"),
                ),
                ("response", models.TextField(verbose_name="Ответ")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "indexes": [
                    models.Index(fields=["id"], name="app_miscell_id_95671d_idx"),
                    models.Index(fields=["title"], name="app_miscell_title_50445f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery_images/", verbose_name="Картинка"
                    ),
                ),
                ("to_show", models.BooleanField(verbose_name="Показать")),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галереи",
                "indexes": [
                    models.Index(fields=["id"], name="app_miscell_id_2fbf82_idx")
                ],
            },
        ),
    ]
