# Generated by Django 5.0.1 on 2024-02-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_miscellaneous", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "ordering": ["-id"],
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
