# Generated by Django 5.0.1 on 2024-02-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_miscellaneous", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Gallery",
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
