# Generated by Django 5.0.1 on 2024-02-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagearticles",
            options={
                "ordering": ["-id"],
                "verbose_name": "Изображение Новостей",
                "verbose_name_plural": "Изображения Новостей",
            },
        ),
        migrations.AlterField(
            model_name="articles",
            name="date_created",
            field=models.DateField(verbose_name="Дата создание"),
        ),
    ]
