# Generated by Django 5.0.1 on 2024-02-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutProfession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="major_benefit_images/")),
            ],
            options={
                "verbose_name": "О Профессии",
                "verbose_name_plural": "О Профессии",
            },
        ),
        migrations.CreateModel(
            name="CourseDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="teacher_images/")),
            ],
            options={
                "verbose_name": "Преподователь",
                "verbose_name_plural": "Преподователи",
            },
        ),
        migrations.CreateModel(
            name="CourseBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "course_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок Стеков",
                "verbose_name_plural": "Блок Стеков",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="course_images/")),
                (
                    "extended_image",
                    models.ImageField(upload_to="extended_course_images/"),
                ),
                ("duration", models.CharField(max_length=255)),
                ("monthly_price", models.FloatField()),
                ("installment_price", models.FloatField()),
                ("lesson_duration", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("timetable", models.CharField(max_length=255)),
                ("free_spots", models.IntegerField()),
                (
                    "about_profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.aboutprofession",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseteacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="EducationBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="education_benefit/")),
            ],
            options={
                "verbose_name": "Плюсы Курса",
                "verbose_name_plural": "Плюсы Курса",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_fdac7e_idx"),
                    models.Index(fields=["title"], name="app_courses_title_8ab5ee_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="aboutprofession",
            name="major_education",
            field=models.ManyToManyField(to="app_courses.educationbenefit"),
        ),
        migrations.CreateModel(
            name="MajorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="major_benefit/")),
            ],
            options={
                "verbose_name": "Плюсы профессии",
                "verbose_name_plural": "Плюсы профессии",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_172f3c_idx"),
                    models.Index(fields=["title"], name="app_courses_title_55d8da_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="aboutprofession",
            name="major_benefit",
            field=models.ManyToManyField(to="app_courses.majorbenefit"),
        ),
        migrations.CreateModel(
            name="TeacherTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("teachers", models.ManyToManyField(to="app_courses.courseteacher")),
            ],
            options={
                "verbose_name": "Технология Преподователя",
                "verbose_name_plural": "Технологии Преподователей",
            },
        ),
        migrations.CreateModel(
            name="BlockSubheading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стеки",
                "verbose_name_plural": "Стеки",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_0fac3f_idx"),
                    models.Index(fields=["title"], name="app_courses_title_2a2dc1_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="courseblock",
            index=models.Index(fields=["id"], name="app_courses_id_e96368_idx"),
        ),
        migrations.AddIndex(
            model_name="courseblock",
            index=models.Index(fields=["title"], name="app_courses_title_6696d4_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["id"], name="app_courses_id_6ef077_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["title"], name="app_courses_title_a94ed3_idx"),
        ),
        migrations.AddIndex(
            model_name="aboutprofession",
            index=models.Index(fields=["id"], name="app_courses_id_251bca_idx"),
        ),
        migrations.AddIndex(
            model_name="aboutprofession",
            index=models.Index(fields=["title"], name="app_courses_title_2121ac_idx"),
        ),
    ]
