# Generated by Django 5.0.1 on 2024-02-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "course_block",
                "verbose_name_plural": "course_blocks",
            },
        ),
        migrations.CreateModel(
            name="CourseDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "course_direction",
                "verbose_name_plural": "course_directions",
            },
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="teacher_images/")),
            ],
            options={
                "verbose_name": "course_teacher",
                "verbose_name_plural": "course_teachers",
            },
        ),
        migrations.CreateModel(
            name="BlockSubheading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "block_subheading",
                "verbose_name_plural": "block_subheadings",
            },
        ),
        migrations.AddField(
            model_name="courseblock",
            name="course_direction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_courses.coursedirection",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="course_images/")),
                (
                    "extended_image",
                    models.ImageField(upload_to="extended_course_images/"),
                ),
                ("duration", models.CharField(max_length=255)),
                ("monthly_price", models.FloatField()),
                ("installment_price", models.FloatField()),
                ("lesson_duration", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("timetable", models.CharField(max_length=255)),
                ("free_spots", models.IntegerField()),
                ("description_title", models.CharField(max_length=255)),
                ("major_description", models.TextField()),
                ("major_image", models.ImageField(upload_to="major_images/")),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseteacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.CreateModel(
            name="EducationBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="education_benefit_images/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "education_benefit",
                "verbose_name_plural": "education_benefits",
            },
        ),
        migrations.CreateModel(
            name="MajorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="major_benefit_images/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "major_benefit",
                "verbose_name_plural": "major_benefits",
            },
        ),
        migrations.CreateModel(
            name="TeacherTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("teachers", models.ManyToManyField(to="app_courses.courseteacher")),
            ],
            options={
                "verbose_name": "teacher_technology",
                "verbose_name_plural": "teacher_technologies",
            },
        ),
    ]
