# Generated by Django 5.0.1 on 2024-02-22 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="EducationBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        upload_to="education_benefit/", verbose_name="Иконка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Плюсы Курса",
                "verbose_name_plural": "Плюсы Курса",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_fdac7e_idx"),
                    models.Index(fields=["title"], name="app_courses_title_8ab5ee_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MajorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        upload_to="major_benefit/", verbose_name="Иконка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Плюсы профессии",
                "verbose_name_plural": "Плюсы профессии",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_172f3c_idx"),
                    models.Index(fields=["title"], name="app_courses_title_55d8da_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AboutProfession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="major_benefit_images/", verbose_name="Картинка"
                    ),
                ),
                (
                    "major_education",
                    models.ManyToManyField(
                        to="app_courses.educationbenefit", verbose_name="Плюсы Курса"
                    ),
                ),
                (
                    "major_benefit",
                    models.ManyToManyField(
                        to="app_courses.majorbenefit", verbose_name="Плюсы профессии"
                    ),
                ),
            ],
            options={
                "verbose_name": "О Профессии",
                "verbose_name_plural": "О Профессии",
            },
        ),
        migrations.CreateModel(
            name="TeacherTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Технологии")),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                        verbose_name="Напрвление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Технология Преподователя",
                "verbose_name_plural": "Технологии Преподователей",
            },
        ),
        migrations.CreateModel(
            name="CourseTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="teacher_images/", verbose_name="Фотография"
                    ),
                ),
                (
                    "technology",
                    models.ManyToManyField(
                        to="app_courses.teachertechnology", verbose_name="Технологии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподователь",
                "verbose_name_plural": "Преподователи",
            },
        ),
        migrations.CreateModel(
            name="TopicProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Загаловка")),
            ],
            options={
                "verbose_name": "Тема курса",
                "verbose_name_plural": "Темы курса",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_d09d56_idx"),
                    models.Index(fields=["title"], name="app_courses_title_fefe59_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовка")),
                (
                    "course_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                        verbose_name="Направление Курса",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        to="app_courses.topicprogram", verbose_name="Темы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа Курса",
                "verbose_name_plural": "Программа Курсов",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="course_images/", verbose_name="Картинка"
                    ),
                ),
                (
                    "extended_image",
                    models.ImageField(
                        upload_to="extended_course_images/", verbose_name="Иконка"
                    ),
                ),
                (
                    "duration",
                    models.CharField(max_length=255, verbose_name="Продолжительность"),
                ),
                ("monthly_price", models.FloatField(verbose_name="Месячная цена")),
                (
                    "installment_price",
                    models.FloatField(verbose_name="Цена в Рассрочку"),
                ),
                (
                    "lesson_duration",
                    models.CharField(
                        max_length=255, verbose_name="Продолжительность урока"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Старт Курса")),
                (
                    "timetable",
                    models.CharField(max_length=255, verbose_name="Расписание"),
                ),
                ("free_spots", models.IntegerField(verbose_name="Свободные места")),
                (
                    "about_profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.aboutprofession",
                        verbose_name="О профессии",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "course_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseprogram",
                        verbose_name="Программа курса",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.courseteacher",
                        verbose_name="Преподователи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_6ef077_idx"),
                    models.Index(fields=["title"], name="app_courses_title_a94ed3_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aboutprofession",
            index=models.Index(fields=["id"], name="app_courses_id_251bca_idx"),
        ),
        migrations.AddIndex(
            model_name="aboutprofession",
            index=models.Index(fields=["title"], name="app_courses_title_2121ac_idx"),
        ),
        migrations.AddIndex(
            model_name="courseteacher",
            index=models.Index(fields=["id"], name="app_courses_id_aae462_idx"),
        ),
        migrations.AddIndex(
            model_name="courseteacher",
            index=models.Index(
                fields=["first_name"], name="app_courses_first_n_46e6bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogram",
            index=models.Index(fields=["id"], name="app_courses_id_341a4a_idx"),
        ),
        migrations.AddIndex(
            model_name="courseprogram",
            index=models.Index(fields=["title"], name="app_courses_title_a45f60_idx"),
        ),
    ]
