# Generated by Django 5.0.1 on 2024-02-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseblock",
            name="course_direction",
        ),
        migrations.CreateModel(
            name="CourseProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "course_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_courses.coursedirection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа Курса",
                "verbose_name_plural": "Программа Курсов",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="course_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_courses.courseprogram",
            ),
        ),
        migrations.CreateModel(
            name="TopicProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Тема курса",
                "verbose_name_plural": "Темы курса",
                "indexes": [
                    models.Index(fields=["id"], name="app_courses_id_d09d56_idx"),
                    models.Index(fields=["title"], name="app_courses_title_fefe59_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="courseprogram",
            name="topic",
            field=models.ManyToManyField(to="app_courses.topicprogram"),
        ),
        migrations.DeleteModel(
            name="BlockSubheading",
        ),
        migrations.DeleteModel(
            name="CourseBlock",
        ),
        migrations.AddIndex(
            model_name="courseprogram",
            index=models.Index(fields=["id"], name="app_courses_id_341a4a_idx"),
        ),
        migrations.AddIndex(
            model_name="courseprogram",
            index=models.Index(fields=["title"], name="app_courses_title_a45f60_idx"),
        ),
    ]
